version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Install Dependencies
          command: |
            apk add rsync
            apk add zip
            apk add openssh-client
            mkdir p ~/.ssh
            chmod 700 ~/.ssh
            mkdir ./resources
      - run:
          name: Download Project
          command: |
            echo $SSH_USERNAME;
            echo $SSH_HOST;
            ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST  "ls;cd /var/www;ls";
            rsync -a --exclude=node_modules --exclude=vendor $SSH_USERNAME@$SSH_HOST:/var/www/cloud-life/* ./resources;
            cd ./resources/;ls;
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /test/new.text;
            echo $TEST > /test/new.text;
            echo $TEST;

      - run:
          name: Compress Project
          command: |
            zip -r resources.zip ./resources
      
      - store_artifacts:
          name: Upload Artifact
          path: ./resources.zip
      