version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "31:26:11:20:e3:11:8b:89:eb:b2:19:1e:92:a7:ef:be"
      - run:
          name: Install Dependencies
          command: |
            apk add rsync

      - run:
          name: Creating Dummy Artifacts
          command: |
            mkdir ./resources
      - run:
          name: Deploy Over SSH
          command: |
            echo $SSH_USERNAME;
            echo $SSH_HOST;
            ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST  "ls;cd /var/www;ls";
            rsync -a --exclude=node_modules --exclude=vendor $SSH_USERNAME@$SSH_HOST:/var/www/cloud-life/* ./resources;
            cd ./resources/;ls;
      #scp -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST:/var/www/cloud-life/.env ./resources;
      # - store_artifacts:
      #     path: ./resources

      # - run:
      #     name: Creating Dummy Artifacts
      #     command: |
      #       echo "my artifact file" > /test/new.text;
      #       echo $TEST > /test/new.text;
      #       echo $TEST;

      # - run:
      #     command: |
      #       zip -r test.zip *
      
      # - store_artifacts:
      #     path: ./test.zip
      