version: 2
jobs:
  build:
    docker:
      - image: cimg/php:7.2.24
    steps:
      - add_ssh_keys:
          fingerprints:
            - "31:26:11:20:e3:11:8b:89:eb:b2:19:1e:92:a7:ef:be"

      - run:
          name: Creating Dummy Artifacts
          command: |
            mkdir ./resources
            ls
            cd ./resources/;ls;
            rsync;

      # - run:
      #     name: Deploy Over SSH
      #     command: |
      #       echo $SSH_USERNAME;
      #       echo $SSH_HOST;
      #       ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST  "ls;cd /var/www;ls";
      #       scp -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST:/var/www/cloud-life/.env ./resources;
      #       cd ./resources/;ls;

      # - store_artifacts:
      #     path: ./resources

      # - run:
      #     name: Creating Dummy Artifacts
      #     command: |
      #       echo "my artifact file" > /test/new.text;
      #       echo $TEST > /test/new.text;
      #       echo $TEST;

      # - run:
      #     command: |
      #       zip -r test.zip *
      
      # - store_artifacts:
      #     path: ./test.zip
      