version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Install Dependencies
          command: |
            apk add rsync
            apk add zip
            apk add openssh-client
            mkdir p ~/.ssh
            chmod 700 ~/.ssh
            mkdir ./resources

      # - add_ssh_keys:
      #     fingerprints:
      #       - "31:26:11:20:e3:11:8b:89:eb:b2:19:1e:92:a7:ef:be"

      - run:
          name: Download Project
          command: |
            echo $SSH_USERNAME;
            echo $SSH_HOST;
            ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST  "ls;cd /var/www;ls";
            rsync -a --exclude=node_modules --exclude=vendor $SSH_USERNAME@$SSH_HOST:/var/www/cloud-life/* ./resources;
            cd ./resources/;ls;
      #scp -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST:/var/www/cloud-life/.env ./resources;
      # - store_artifacts:
      #     path: ./resources

      # - run:
      #     name: Creating Dummy Artifacts
      #     command: |
      #       echo "my artifact file" > /test/new.text;
      #       echo $TEST > /test/new.text;
      #       echo $TEST;

      # - run:
      #     command: |
      #       zip -r test.zip *
      
      # - store_artifacts:
      #     path: ./test.zip
      