# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: 7.4.24-browsers
    working_directory: /test
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /test/new.text;

      - store_artifacts:
          path: /test
          destination: new.text

      - run:
          uses: montudor/action-zip@v1
          name: Create ZIP File
          command: |
            echo "my artifact file" > /test/new.text;
