version: 2
jobs:
  build:
    docker:
      - image: cimg/php:7.2.24
    working_directory: /test
    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /test/new.text;

      - run:
          command: |
            zip test.zip ./test
      
      - store_artifacts:
          path: ./test.zip